# Generated by Django 5.0.4 on 2024-05-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_blog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
