# Generated by Django 5.0.4 on 2024-05-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="postTime",
            field=models.DateField(auto_now_add=True),
        ),
    ]
