# Generated by Django 5.0.4 on 2024-05-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_blog_posttime"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
