# Generated by Django 5.0.4 on 2024-05-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_delete_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("blogNo", models.AutoField(primary_key=True, serialize=False)),
                ("blogTitle", models.CharField(max_length=200)),
                ("blogPreviewBody", models.TextField()),
                ("blogContent", models.TextField()),
                ("slug", models.CharField(max_length=100)),
                ("blogAuthor", models.CharField(max_length=50)),
                ("postTime", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
