# Generated by Django 5.0.4 on 2024-05-20 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_blog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
