# Generated by Django 5.0.4 on 2024-05-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_delete_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("blogNo", models.AutoField(primary_key=True, serialize=False)),
                ("blogTitle", models.CharField(max_length=200)),
                ("blogPreviewBody", models.TextField()),
                ("blogContentIntro", models.TextField()),
                ("blogTopic1", models.CharField(max_length=200)),
                ("blogTopic1Content", models.TextField()),
                ("blogTopic2", models.CharField(max_length=200)),
                ("blogTopic2Content", models.TextField()),
                ("blogTopic3", models.CharField(max_length=200)),
                ("blogTopic3Content", models.TextField()),
                ("blogTopic4", models.CharField(max_length=200)),
                ("blogTopic4Content", models.TextField()),
                ("blogConclusionHeading", models.CharField(max_length=200)),
                ("blogConclusionContent", models.TextField()),
                ("slug", models.CharField(max_length=100)),
                ("blogAuthor", models.CharField(max_length=50)),
                ("postTime", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
