# Generated by Django 5.0.4 on 2024-05-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_blog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
