# Generated by Django 5.0.4 on 2024-05-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="blogImage",
            field=models.ImageField(blank=True, null=True, upload_to="blog-section/"),
        ),
    ]
