# Generated by Django 5.0.4 on 2024-05-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_blog_blogimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blogImage",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/blog-section/"
            ),
        ),
    ]
