# Generated by Django 5.0.4 on 2024-05-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_alter_blog_blogimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blogImage",
            field=models.ImageField(default="", upload_to="static/blog-section/"),
        ),
    ]
