# Generated by Django 5.0.4 on 2024-09-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="feature_on_home",
            field=models.BooleanField(default=False),
        ),
    ]
