# Generated by Django 5.0.4 on 2024-10-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_feedback_feature_on_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="feature_on_home",
            field=models.BooleanField(default=False),
        ),
    ]
