# Generated by Django 5.0.4 on 2024-10-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_blog_feature_on_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="feature_on_blog_highlights",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blog",
            name="feature_on_blog_latest_posts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blog",
            name="feature_on_blog_popular_posts",
            field=models.BooleanField(default=False),
        ),
    ]
