# Generated by Django 5.0.4 on 2024-10-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="dashboardWc/user-circle_svgrepo.com.png",
                upload_to="profile_pics/",
            ),
        ),
    ]
