# Generated by Django 5.0.4 on 2024-10-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
