# Generated by Django 5.0.4 on 2024-10-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pics/user-circle_svgrepo.com.png",
                upload_to="profile_pics/",
            ),
        ),
    ]
