# Generated by Django 5.0.4 on 2024-10-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0031_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
