# Generated by Django 5.0.4 on 2024-10-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0032_remove_profile_profile_picture_profile_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_verified",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pics/user-circle_svgrepo.com.png",
                upload_to="profile_pics/",
            ),
        ),
    ]
