# Generated by Django 5.0.4 on 2024-10-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0033_remove_profile_is_verified_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
