# Generated by Django 5.0.4 on 2025-01-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0035_exportcount_resumecount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExportCount",
        ),
    ]
