# Generated by Django 4.2.27 on 2025-12-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_cvtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(default='Smart Parichaya', max_length=255)),
                ('description', models.TextField()),
                ('skills', models.TextField(help_text='Enter skills separated by commas (e.g. Python, SQL, Design)')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.DeleteModel(
            name='CVTemplate',
        ),
    ]
